apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world
  namespace: argo-rollouts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hashicorp/http-echo
        args:
        - "-text=Hello World!"
        ports:
        - containerPort: 5678
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
      - setWeight: 100
